BopHub/Models/Bops/BopsDetailModel.cs
using BopHub.Models.Validation;
using BopHubData.Model;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BopHub.Models.Bops
{
    public class BopsDetailModel
    {
        public int BopId { get; set; }
        [Required]
        [StringLength(40), MinLength(4)]
        public string BopName { get; set; }
        [Required] public string Artiste { get; set; }
        [Required] [FutureDate] public string ReleaseDate { get; set; }
        [Required] public string ReleaseTime { get; set; }
        [Required]
        public string ReleaseVenue { get; set; }
        [Required]
        public int Genre { get; set; }
        public IEnumerable<Genre> Genres { get; set; }
    }
}

BopHub/Models/Bops/BopsListingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BopHub.Models.Bops
{
    public class BopsListingModel
    {
        public IEnumerable<BopsDetailModel> BopsDetailsList { get; set; }
    }
}

BopHub/Controllers/BopsController.cs
using BopHub.Models;
using BopHub.Models.Bops;
using BopHubData.Model;
using BopHubData.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BopHub.Controllers
{
    public class BopsController : Controller
    {
        private readonly IRepository<Genre> genre;
        private readonly IRepository<Bop> bop;
        private readonly IRepository<Account> account;

        public BopsController(IRepository<Genre> genre, IRepository<Bop> bop, IRepository<Account> account)
        {
            this.genre = genre;
            this.bop = bop;
            this.account = account;
        }

        public async Task<IActionResult> Create()
        {
            var genreList = await genre.GetAllAsync();
            var model = new BopsDetailModel
            {
                Genres = genreList
            };
            //dynamic modelNav = new NavBarViewModel
            //{
            //    BopModel = model
            //};
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] BopsDetailModel bopsDetail)
        {
            if (!ModelState.IsValid)
            {
                bopsDetail.Genres = await genre.GetAllAsync();
                return View("Create", bopsDetail);
            }
                
            var artiste = await account.Find(x => x.Id == 1);
            var model = new Bop()
            {
                Artiste = artiste,
                ReleaseDate = DateTime.Parse(bopsDetail.ReleaseDate),
                Genre = await genre.Find(x => x.Id == bopsDetail.Genre),
                ReleaseVenue = "Lagos",
                BopName = bopsDetail.BopName,
            };
            bop.Add(model);
            bop.Save();
            return RedirectToAction("Index", "Home");
        }
    }
}

BopHub/Views/Bops/Create.cshtml
@model BopHub.Models.Bops.BopsDetailModel

@{
    ViewData["Title"] = "Create Bops";
}

<h2>Add a Bop</h2>
<p class="alert alert-info">All fields are <strong>required</strong></p>
<form method="post">
    @Html.AntiForgeryToken()
    <div class="col-md-3">
        <div asp-validation-summary="@ValidationSummary.ModelOnly"></div>
        <input type="hidden" id="artiste" class="form-control" asp-for="@Model.BopId" />
        <div class="form-group">
            <label asp-for="@Model.Artiste"></label>
            <input type="text" autofocus="autofocus" id="artiste" class="form-control" asp-for="@Model.Artiste" />
            <span asp-validation-for="@Model.Artiste"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.BopName"></label>
            <input type="text" id="bopName" class="form-control" asp-for="@Model.BopName" />
            <span asp-validation-for="@Model.BopName"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.ReleaseDate">Release Date</label>
            <input type="text" id="releaseDate" class="form-control" asp-for="@Model.ReleaseDate" placeholder="01 01 2020" />
            <span asp-validation-for="@Model.ReleaseDate"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.ReleaseTime">Release Time</label>
            <input type="text" id="releaseTime" class="form-control" asp-for="@Model.ReleaseTime" />
        </div>
        <div class="form-group">
            <label asp-for="@Model.Genre">Genre</label>
            <select asp-for="@Model.Genre" class="form-control" asp-items="@(new SelectList(@Model.Genres, "Id", "Name"))">
                <option value=""></option>
            </select>
            <span asp-validation-for="@Model.Genre"></span>
        </div>
        <button type="submit" class="btn btn-secondary" asp-action="Create" asp-controller="Bops">Create Bop</button>
    </div>

</form>